_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

# AcmeDemoBundle routes (to be removed)
_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

# AcmeBlogBundle routes
post:
    pattern: /post/
    defaults: { _controller: AcmeBlogBundle:Post:index }
post_new:
    pattern: /post_new
    defaults: { _controller: AcmeBlogBundle:Post:new }
post_create:
    pattern: /post_create
    defaults: { _controller: AcmeBlogBundle:Post:create }
post_show:
    pattern: /post_show/{id}
    defaults: { _controller: AcmeBlogBundle:Post:show }
post_edit:
    pattern: /{id}/edit
    defaults: { _controller: AcmeBlogBundle:Post:edit }
post_delete:
    pattern: /{id}
    defaults: { _controller: AcmeBlogBundle:Post:delete }
post_update:
    pattern: /{id}
    defaults: { _controller: AcmeBlogBundle:Post:update }
